# Generated by Django 4.2.7 on 2024-02-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Add_tenant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
