# Generated by Django 4.2.7 on 2024-02-16 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Add_tenant', '0005_lessorname_place_delete_lessor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessorName',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
        migrations.DeleteModel(
            name='Treaty',
        ),
    ]
