# Generated by Django 4.2.7 on 2024-02-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Add_tenant', '0006_delete_lessorname_delete_place_delete_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessorName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessor_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tenant_name', models.CharField(max_length=255)),
                ('lot_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Treaty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treaty_date', models.DateField()),
                ('treaty_number', models.CharField(max_length=255)),
                ('treaty_type', models.CharField(max_length=255)),
            ],
        ),
    ]
